### ISSUE TITLE
RFD868x after bad firmware changed frequency to 915MHz

### ISSUE THREAD

**Issue by mop98915** [ArduPilot/SiK#61]
RFD868x after bad firmware changed frequency to 915MHz.
How to go back to 868MHz?
![868](https://user-images.githubusercontent.com/5208127/88397935-8bba2780-cdbc-11ea-9b3a-1b97fbc10157.png)

**Comment by jayzosayers** [comment]
Did you resolve this? I've just had this issue occur. The manual mentions the issue but says nothing about how to resolve it.

**Comment by mop98915** [comment]
Hi

I had to send the unit back to rfdesigns to replace for a new one.

Best regards
Hugo

A quinta, 25/11/2021, 01:53, jayzosayers ***@***.***>
escreveu:
