### ISSUE TITLE
The radio cannot enter AT after modifying parameters

### ISSUE THREAD

**Issue by suiaiyun** [ArduPilot/SiK#73]
The main control chip uses c8051f931. After flashing the firmware, use + + + to enter the at configuration command line. After saving the parameters with AT&W and restarting, try to enter at with + + + again, and the radio doesn't respond

**Comment by povik** [comment]
Possibly related: https://github.com/ArduPilot/SiK/pull/68

You can apply the fix there and see if that fixes this issue too.

**Comment by suiaiyun** [comment]
> Possibly related: #68
> 
> You can apply the fix there and see if that fixes this issue too.

That's great. Thank you for your method. It's very useful and solves my problem.
