### ISSUE TITLE
Command mode failure after AT&W - resulting in inability to flash unless forced into bootloader.

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/SiK#74]
@tridge - please verify yourself - this is how it looks on my end:

I compile the current master and upload with --resetparams
All good, the hm_trp works just fine.
..and the command mode will fail permanently after AT&W (storing parameters to EEPROM)

To reproduce:
Flash current master to HM-TRP (probably others will have this issue too)
enter command mode in terminal, issue AT&W , ATZ    (no need to actually change any setting)

Observe that you get echo after "+++"   - but never an "OK" , in fact, no command return any output.
There is no way to change anything in command mode.

The only way to recover is to pull CTS down when booting, to force bootload mode.
The latest build of 2.0 does not have this issue.

**Comment by suiaiyun** [comment]
Please refer to this case. #73 
I have encountered the same problem as you

**Comment by AndKe** [comment]
Thank you  PR https://github.com/ArduPilot/SiK/pull/68 seems to fix it.

**Comment by kaklik** [comment]
That seems to be resolved. Close it, please.
